"use client";
import React from "react";
import AppProvider from "@/Redux/AppProvider";
import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import { usePathname } from "next/navigation";
import Sidebar from "@/components/common/Sidebar";
import { IconButton } from "@chakra-ui/react";
import { FaArrowUp } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Clouder",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          {pathname === "/" && <Navbar />}
          {pathname === "/dashboard" && <Sidebar />}
          {children}
          {pathname === "/" && <Footer />}
          {/* back top button */}

          <IconButton
            aria-label="back-to-top"
            pos={"fixed"}
            right={["1rem", "3rem", "4rem", "5rem"]}
            bottom={["1rem", "1.5rem", "2rem"]}
            icon={<FaArrowUp />}
            boxSize={["2.5rem", "3.5rem", ""]}
            fontSize={["1rem", null, "1.5rem"]}
            cursor={"pointer"}
            color={"white"}
            bgColor={"primary_2"}
            href="#top"
            as="a"
            rounded={"full"}
            _hover={{}}
            _active={{}}
          />
        </AppProvider>
      </body>
    </html>
  );
}
