
import AppProvider from "@/Redux/AppProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/common/Sidebar";
import Navbar from "@/components/common/Navbar";
import { Footer } from "@/components/common/Footer";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clouder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const router = useRouter();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <Navbar />
          {/* {router.prefe === "/dashboard" && <Sidebar />} */}
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
