"use client";
import React from "react";
import AppProvider from "@/Redux/AppProvider";
import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/common/Navbar";
import { Footer } from "@/components/common/Footer";
import { usePathname } from "next/navigation";
import Sidebar from "@/components/common/Sidebar";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Clouder",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          {pathname === "/" && <Navbar />}
          {pathname === "/dashboard" && <Sidebar />}
          {children}
          {pathname === "/" && <Footer />}
        </AppProvider>
      </body>
    </html>
  );
}
